# Maps glyph spell name -> icon name of the spell it modifies
# Covers all WotLK classes: Warrior, Paladin, Hunter, Rogue, Priest,
# Death Knight, Shaman, Mage, Warlock, Druid
GLYPH_ICON_MAP: dict[str, str] = {

    # Death Knight
    "Glyph of Anti-Magic Shell":           "spell_shadow_antimagicshell",
    "Glyph of Blood Strike":               "Spell_deathknight_deathstrike",
    "Glyph of Blood Tap":                  "spell_deathknight_bloodtap",
    "Glyph of Bone Shield":                "inv_chest_leather_13",
    "Glyph of Corpse Explosion":           "ability_creature_disease_02",
    "Glyph of Dancing Rune Weapon":        "inv_sword_07",
    "Glyph of Dark Command":               "spell_nature_shamanrage",
    "Glyph of Dark Death":                 "spell_shadow_deathcoil",
    "Glyph of Death and Decay":            "spell_shadow_deathanddecay",
    "Glyph of Death Grip":                 "spell_deathknight_strangulate",
    "Glyph of Death Strike":               "spell_deathknight_butcher2",
    "Glyph of Death's Embrace":            "spell_shadow_deathcoil",
    "Glyph of Disease":                    "spell_shadow_plaguecloud",
    "Glyph of Frost Strike":               "Spell_deathknight_empowerruneblade2",
    "Glyph of Heart Strike":               "inv_weapon_shortblade_40",
    "Glyph of Horn of Winter":             "inv_misc_horn_02",
    "Glyph of Howling Blast":              "spell_frost_arcticwinds",
    "Glyph of Hungering Cold":             "inv_staff_15",
    "Glyph of Chains of Ice":              "spell_frost_chainsofice",
    "Glyph of Icebound Fortitude":         "spell_deathknight_iceboundfortitude",
    "Glyph of Icy Touch":                  "spell_deathknight_icetouch",
    "Glyph of Obliterate":                 "Spell_deathknight_classicon",
    "Glyph of Pestilence":                 "spell_shadow_plaguecloud",
    "Glyph of Plague Strike":              "Spell_deathknight_empowerruneblade",
    "Glyph of Raise Dead":                 "spell_shadow_animatedead",
    "Glyph of Rune Strike":                "spell_deathknight_darkconviction",
    "Glyph of Rune Tap":                   "spell_deathknight_runetap",
    "Glyph of Strangulate":                "spell_shadow_soulleech_3",
    "Glyph of the Ghoul":                  "spell_shadow_animatedead",
    "Glyph of Unbreakable Armor":          "inv_armor_helm_plate_naxxramas_raidwarrior_c_01",
    "Glyph of Unholy Blight":              "spell_shadow_contagion",
    "Glyph of Vampiric Blood":             "spell_shadow_lifedrain",

    # Druid
    "Glyph of Aquatic Form":               "ability_druid_aquaticform",
    "Glyph of Barkskin":                   "spell_nature_stoneclawtotem",
    "Glyph of Berserk":                    "ability_druid_berserk",
    "Glyph of Dash":                       "ability_druid_dash",
    "Glyph of Entangling Roots":           "spell_nature_stranglevines",
    "Glyph of Frenzied Regeneration":      "ability_bullrush",
    "Glyph of Growling":                   "ability_physical_taunt",
    "Glyph of Healing Touch":              "spell_nature_healingtouch",
    "Glyph of Hurricane":                  "spell_nature_cyclone",
    "Glyph of Challenging Roar":           "ability_druid_challengingroar",
    "Glyph of Innervate":                  "spell_nature_lightning",
    "Glyph of Insect Swarm":               "spell_nature_insectswarm",
    "Glyph of Lifebloom":                  "inv_misc_herb_felblossom",
    "Glyph of Mangle":                     "ability_druid_mangle2",
    "Glyph of Maul":                       "ability_druid_maul",
    "Glyph of Monsoon":                    "ability_druid_typhoon",
    "Glyph of Moonfire":                   "spell_nature_starfall",
    "Glyph of Natural Force":              "spell_nature_abolishmagic",
    "Glyph of Nourish":                    "ability_druid_nourish",
    "Glyph of Omen of Clarity":            "spell_nature_crystalball",
    "Glyph of Rake":                       "ability_druid_disembowel",
    "Glyph of Rapid Rejuvenation":         "spell_nature_rejuvenation",
    "Glyph of Rebirth":                    "spell_nature_reincarnation",
    "Glyph of Regrowth":                   "spell_nature_resistnature",
    "Glyph of Rejuvenation":               "spell_nature_rejuvenation",
    "Glyph of Rip":                        "ability_ghoulfrenzy",
    "Glyph of Shred":                      "spell_shadow_vampiricaura",
    "Glyph of Starfall":                   "ability_druid_starfall",
    "Glyph of Starfire":                   "spell_arcane_starfire",
    "Glyph of Survival Instincts":         "ability_druid_tigersroar",
    "Glyph of Swiftmend":                  "inv_relics_idolofrejuvenation",
    "Glyph of the Wild":                   "spell_nature_giftofthewild",
    "Glyph of Thorns":                     "spell_nature_thorns",
    "Glyph of Typhoon":                    "ability_druid_typhoon",
    "Glyph of Wild Growth":                "ability_druid_flourish",
    "Glyph of Wrath":                      "Spell_nature_abolishmagic",

    # Hunter
    "Glyph of Aimed Shot":                 "inv_spear_07",
    "Glyph of Arcane Shot":                "ability_impalingbolt",
    "Glyph of Aspect of the Viper":        "ability_hunter_aspectoftheviper",
    "Glyph of Bestial Wrath":              "ability_druid_ferociousbite",
    "Glyph of Deterrence":                 "ability_whirlwind",
    "Glyph of Disengage":                  "ability_rogue_feint",
    "Glyph of Explosive Shot":             "ability_hunter_explosiveshot",
    "Glyph of Explosive Trap":             "spell_fire_selfdestruct",
    "Glyph of Feign Death":                "ability_rogue_feigndeath",
    "Glyph of Freezing Trap":              "spell_frost_chainsofice",
    "Glyph of Frost Trap":                 "spell_frost_frostnova",
    "Glyph of Hunter's Mark":              "ability_hunter_snipershot",
    "Glyph of Chimera Shot":               "ability_hunter_chimerashot2",
    "Glyph of Immolation Trap":            "spell_fire_flameshock",
    "Glyph of Kill Shot":                  "ability_hunter_assassinate2",
    "Glyph of Mend Pet":                   "ability_hunter_mendpet",
    "Glyph of Mending":                    "ability_hunter_mendpet",
    "Glyph of Multi-Shot":                 "ability_upgrademoonglaive",
    "Glyph of Possessed Strength":         "ability_eyeoftheowl",
    "Glyph of Rapid Fire":                 "ability_hunter_runningshot",
    "Glyph of Raptor Strike":              "ability_meleedamage",
    "Glyph of Revive Pet":                 "ability_hunter_beastsoothe",
    "Glyph of Scare Beast":                "ability_druid_cower",
    "Glyph of Scatter Shot":               "ability_golemstormbolt",
    "Glyph of Serpent Sting":              "ability_hunter_quickshot",
    "Glyph of Snake Trap":                 "ability_hunter_snaketrap",
    "Glyph of Steady Shot":                "ability_hunter_steadyshot",
    "Glyph of the Beast":                  "ability_mount_pinktiger",
    "Glyph of the Hawk":                   "spell_nature_ravenform",
    "Glyph of the Pack":                   "ability_mount_whitetiger",
    "Glyph of Trueshot Aura":              "ability_trueshot",
    "Glyph of Volley":                     "ability_marksmanship",
    "Glyph of Wyvern Sting":               "inv_spear_02",

    # Mage
    "Glyph of Arcane Barrage":             "ability_mage_arcanebarrage",
    "Glyph of Arcane Blast":               "spell_arcane_blast",
    "Glyph of Arcane Explosion":           "spell_nature_wispsplode",
    "Glyph of Arcane Intellect":           "spell_holy_magicalsentry",
    "Glyph of Arcane Missiles":            "spell_nature_starfall",
    "Glyph of Arcane Power":               "spell_nature_lightning",
    "Glyph of Blast Wave":                 "spell_holy_excorcism_02",
    "Glyph of Blink":                      "spell_arcane_blink",
    "Glyph of Deep Freeze":                "ability_mage_deepfreeze",
    "Glyph of Eternal Water":              "spell_frost_summonwaterelemental_2",
    "Glyph of Evocation":                  "spell_nature_purge",
    "Glyph of Fire Blast":                 "spell_fire_fireball",
    "Glyph of Fire Ward":                  "spell_fire_firearmor",
    "Glyph of Fireball":                   "spell_fire_flamebolt",
    "Glyph of Frost Armor":                "spell_frost_frostarmor02",
    "Glyph of Frost Nova":                 "spell_frost_frostnova",
    "Glyph of Frost Ward":                 "spell_frost_frostward",
    "Glyph of Frostbolt":                  "spell_frost_frostbolt02",
    "Glyph of Frostfire":                  "ability_mage_frostfirebolt",
    "Glyph of Ice Armor":                  "spell_frost_frostarmor02",
    "Glyph of Ice Barrier":                "spell_ice_lament",
    "Glyph of Ice Block":                  "spell_frost_frost",
    "Glyph of Ice Lance":                  "spell_frost_frostblast",
    "Glyph of Icy Veins":                  "spell_frost_coldhearted",
    "Glyph of Invisibility":               "ability_mage_invisibility",
    "Glyph of Living Bomb":                "ability_mage_livingbomb",
    "Glyph of Mage Armor":                 "spell_magearmor",
    "Glyph of Mana Gem":                   "inv_misc_gem_sapphire_02",
    "Glyph of Mirror Image":               "spell_magic_lesserinvisibilty",
    "Glyph of Molten Armor":               "ability_mage_moltenarmor",
    "Glyph of Polymorph":                  "spell_nature_polymorph",
    "Glyph of Remove Curse":               "spell_nature_removecurse",
    "Glyph of Scorch":                     "spell_fire_soulburn",
    "Glyph of Slow Fall":                  "spell_magic_featherfall",
    "Glyph of Water Elemental":            "spell_frost_summonwaterelemental_2",
    
    #Paladin
    "Glyph of Avenger's Shield":            "spell_holy_avengersshield",
    "Glyph of Avenging Wrath":              "spell_holy_avenginewrath",
    "Glyph of Beacon of Light":             "ability_paladin_beaconoflight",
    "Glyph of Blessing of Kings":           "spell_magic_magearmor",
    "Glyph of Blessing of Might":           "spell_holy_fistofjustice",
    "Glyph of Blessing of Wisdom":          "Spell_holy_sealofwisdom",
    "Glyph of Cleansing":                   "spell_holy_purify",
    "Glyph of Consecration":                "spell_holy_innerfire",
    "Glyph of Crusader Strike":             "spell_holy_crusaderstrike",
    "Glyph of Divine Plea":                 "spell_holy_aspiration",
    "Glyph of Divine Storm":                "ability_paladin_divinestorm",
    "Glyph of Divinity":                    "spell_holy_layonhands",
    "Glyph of Exorcism":                    "spell_holy_exorcism_02",
    "Glyph of Flash of Light":              "spell_holy_flashheal",
    "Glyph of Hammer of Justice":           "spell_holy_sealofmight",
    "Glyph of Hammer of the Righteous":     "ability_paladin_hammeroftherighteous",
    "Glyph of Hammer of Wrath":             "ability_thunderclap",
    "Glyph of Holy Light":                  "spell_holy_holybolt",
    "Glyph of Holy Shock":                  "spell_holy_searinglight",
    "Glyph of Holy Wrath":                  "spell_holy_excorcism",
    "Glyph of Judgement":                   "spell_holy_righteousfury",
    "Glyph of Lay on Hands":                "spell_holy_layonhands",
    "Glyph of Reckoning":                   "spell_holy_unyieldingfaith",
    "Glyph of Righteous Defense":           "inv_shoulder_37",
    "Glyph of Salvation":                   "Spell_holy_sealofsacrifice",
    "Glyph of Seal of Command":             "ability_warrior_innerrage",
    "Glyph of Seal of Light":               "spell_holy_healingaura",
    "Glyph of Seal of Righteousness":       "ability_thunderbolt",
    "Glyph of Seal of Vengeance":           "spell_holy_sealofvengeance",
    "Glyph of Seal of Wisdom":              "Spell_holy_righteousnessaura",
    "Glyph of Sense Undead":                "spell_holy_senseundead",
    "Glyph of Shield of Righteousness":     "ability_paladin_shieldofvengeance",
    "Glyph of Spiritual Attunement":        "spell_holy_revivechampion",
    "Glyph of the Wise":                    "Spell_holy_righteousnessaura",
    "Glyph of Turn Evil":                   "spell_holy_turnundead",

    # Priest
    "Glyph of Circle of Healing":          "spell_holy_circleofrenewal",
    "Glyph of Dispel Magic":               "spell_holy_dispelmagic",
    "Glyph of Dispersion":                 "spell_shadow_dispersion",
    "Glyph of Fade":                       "spell_magic_lesserinvisibilty",
    "Glyph of Fading":                     "spell_magic_lesserinvisibilty",
    "Glyph of Fear Ward":                  "spell_holy_excorcism",
    "Glyph of Flash Heal":                 "spell_holy_flashheal",
    "Glyph of Fortitude":                  "spell_holy_wordfortitude",
    "Glyph of Holy Nova":                  "spell_holy_holynova",
    "Glyph of Hymn of Hope":               "spell_holy_symbolofhope",
    "Glyph of Inner Fire":                 "spell_holy_innerfire",
    "Glyph of Levitate":                   "spell_holy_layonhands",
    "Glyph of Lightwell":                  "spell_holy_summonlightwell",
    "Glyph of Mass Dispel":                "spell_arcane_massdispel",
    "Glyph of Mind Control":               "spell_shadow_shadowworddominate",
    "Glyph of Mind Flay":                  "spell_shadow_siphonmana",
    "Glyph of Mind Sear":                  "spell_shadow_mindshear",
    "Glyph of Pain Suppression":           "spell_holy_painsupression",
    "Glyph of Penance":                    "spell_holy_penance",
    "Glyph of Power Word: Shield":         "spell_holy_powerwordshield",
    "Glyph of Prayer of Healing":          "spell_holy_prayerofhealing02",
    "Glyph of Psychic Scream":             "spell_shadow_psychicscream",
    "Glyph of Renew":                      "spell_holy_renew",
    "Glyph of Shackle Undead":             "spell_nature_slow",
    "Glyph of Shadow":                     "spell_shadow_shadowform",
    "Glyph of Shadow Protection":          "spell_shadow_antishadow",
    "Glyph of Shadow Word: Death":         "spell_shadow_demonicfortitude",
    "Glyph of Shadow Word: Pain":          "spell_shadow_shadowwordpain",
    "Glyph of Shadowfiend":                "spell_shadow_shadowfiend",
    "Glyph of Smite":                      "spell_holy_holysmite",
    "Glyph of Spirit of Redemption":       "spell_holy_greaterheal",

    # Rogue
    "Glyph of Adrenaline Rush":            "spell_shadow_shadowworddominate",
    "Glyph of Ambush":                     "ability_rogue_ambush",
    "Glyph of Backstab":                   "ability_backstab",
    "Glyph of Blade Flurry":               "ability_warrior_punishingblow",
    "Glyph of Blurred Speed":              "ability_rogue_sprint", 
    "Glyph of Cloack of Shadows":          "spell_shadow_nethercloak", 
    "Glyph of Crippling Poison":           "ability_poisonsting",
    "Glyph of Deadly Throw":               "inv_throwingknife_06",
    "Glyph of Distract":                   "ability_rogue_distract",
    "Glyph of Envenom":                    "ability_rogue_disembowel",
    "Glyph of Evasion":                    "spell_shadow_shadowward",
    "Glyph of Eviscerate":                 "ability_rogue_eviscerate",
    "Glyph of Expose Armor":               "ability_warrior_riposte",
    "Glyph of Fan of Knives":              "ability_rogue_fanofknives",
    "Glyph of Feint":                      "ability_rogue_feint",
    "Glyph of Garrote":                    "Ability_rogue_garrote",
    "Glyph of Ghostly Strike":             "spell_shadow_curse",
    "Glyph of Gouge":                      "ability_gouge",
    "Glyph of Hemorrhage":                 "spell_shadow_lifedrain",
    "Glyph of Hunger for Blood":           "ability_rogue_hungerforblood",
    "Glyph of Killing Spree":              "ability_rogue_murderspree",
    "Glyph of Mutilate":                   "ability_rogue_shadowstrikes",
    "Glyph of Pick Lock":                  "spell_nature_moonkey",
    "Glyph of Pick Pocket":                "inv_misc_bag_11",
    "Glyph of Preparation":                "spell_shadow_antishadow",
    "Glyph of Rupture":                    "ability_rogue_rupture",
    "Glyph of Safe Fall":                  "inv_feather_01",
    "Glyph of Sap":                        "ability_sap",
    "Glyph of Shadow Dance":               "ability_rogue_shadowdance",
    "Glyph of Sinister Strike":            "spell_shadow_ritualofsacrifice",
    "Glyph of Slice and Dice":             "ability_rogue_slicedice",
    "Glyph of Sprint":                     "ability_rogue_sprint",
    "Glyph of Tricks of the Trade":        "ability_rogue_tricksofthetrade",
    "Glyph of Vanish":                     "ability_vanish",
    "Glyph of Vigor":                      "spell_nature_earthbindtotem",

    # Shaman
    "Glyph of Astral Recall":              "spell_nature_astralrecal",
    "Glyph of Earth Shield":               "spell_nature_skinofearth",
    "Glyph of Earthliving Weapon":         "spell_shaman_earthlivingweapon",
    "Glyph of Elemental Mastery":          "spell_nature_wispheal",
    "Glyph of Feral Spirit":               "spell_shaman_feralspirit",
    "Glyph of Fire Elemental Totem":       "spell_fire_elemental_totem",
    "Glyph of Fire Nova":                  "spell_fire_sealoffire",
    "Glyph of Flame Shock":                "spell_fire_flameshock",
    "Glyph of Flametongue Weapon":         "spell_fire_flametounge",
    "Glyph of Frost Shock":                "spell_frost_frostshock",
    "Glyph of Ghost Wolf":                 "spell_nature_spiritwolf",
    "Glyph of Healing Stream Totem":       "inv_spear_04",
    "Glyph of Healing Wave":               "spell_nature_magicimmunity",
    "Glyph of Hex":                        "spell_shaman_hex",
    "Glyph of Chain Heal":                 "spell_nature_healingwavegreater",
    "Glyph of Chain Lightning":            "spell_nature_chainlightning",
    "Glyph of Lava":                       "spell_shaman_lavaburst",
    "Glyph of Lava Lash":                  "ability_shaman_lavalash",
    "Glyph of Lesser Healing Wave":        "spell_nature_healingwavelesser",
    "Glyph of Lightning Bolt":             "spell_nature_lightning",
    "Glyph of Lightning Shield":           "spell_nature_lightningshield",
    "Glyph of Mana Tide Totem":            "spell_frost_summonwaterelemental",
    "Glyph of Renewed Life":               "spell_nature_reincarnation",
    "Glyph of Riptide":                    "spell_nature_riptide",
    "Glyph of Shocking":                   "spell_nature_earthshock",
    "Glyph of Stoneclaw Totem":            "spell_nature_stoneclawtotem",
    "Glyph of Stormstrike":                "ability_shaman_stormstrike",
    "Glyph of Thunder":                    "spell_shaman_thunderstorm",
    "Glyph of Thunderstorm":               "spell_shaman_thunderstorm",
    "Glyph of Totem of Wrath":             "spell_fire_totemofwrath",
    "Glyph of Water Breathing":            "spell_shadow_demonbreath",
    "Glyph of Water Mastery":              "ability_shaman_watershield",
    "Glyph of Water Shield":               "ability_shaman_watershield",
    "Glyph of Water Walking":              "spell_frost_windwalkon",
    "Glyph of Windfury Weapon":            "spell_nature_cyclone",

    # Warlock
    "Glyph of Conflagrate":                "spell_fire_fireball",
    "Glyph of Corruption":                 "spell_shadow_abominationexplosion",
    "Glyph of Curse of Agony":             "spell_shadow_curseofsargeras",
    "Glyph of Curse of Exhaustion":        "spell_shadow_grimward",
    "Glyph of Death Coil":                 "spell_shadow_deathcoil",
    "Glyph of Demonic Circle":             "ability_warlock_demoniccirclesummon",
    "Glyph of Fear":                       "spell_shadow_possession",
    "Glyph of Felguard":                   "spell_shadow_summonfelguard",
    "Glyph of Felhunter":                  "spell_shadow_summonfelhunter",
    "Glyph of Haunt":                      "ability_warlock_haunt",
    "Glyph of Health Funnel":              "spell_shadow_lifedrain",
    "Glyph of Healthstone":                "inv_stone_04",
    "Glyph of Howl of Terror":             "spell_shadow_deathscream",
    "Glyph of Chaos Bolt":                 "ability_warlock_chaosbolt",
    "Glyph of Immolate":                   "spell_fire_immolation",
    "Glyph of Hellfire":                   "spell_fire_incinerate",
    "Glyph of Imp":                        "spell_shadow_summonimp",
    "Glyph of Incinerate":                 "spell_fire_burnout",
    "Glyph of Kilrogg":                    "spell_shadow_evileye",
    "Glyph of Metamorphosis":              "spell_shadow_demonform",
    "Glyph of Quick Decay":                "spell_shadow_abominationexplosion",
    "Glyph of Searing Pain":               "spell_fire_soulburn",
    "Glyph of Shadow Bolt":                "spell_shadow_shadowbolt",
    "Glyph of Shadowburn":                 "spell_shadow_scourgebuild",
    "Glyph of Shadowflame":                "ability_warlock_shadowflame",
    "Glyph of Siphon Life":                "spell_shadow_requiem",
    "Glyph of Soul Link":                  "spell_shadow_gathershadows",
    "Glyph of Souls":                      "spell_shadow_shadesofdarkness",
    "Glyph of Soulstone":                  "spell_shadow_soulgem",
    "Glyph of Subjugate Demon":            "spell_shadow_enslavedemon",
    "Glyph of Succubus":                   "spell_shadow_summonsuccubus",
    "Glyph of Unending Breath":            "spell_shadow_demonbreath",
    "Glyph of Unstable Affliction":        "spell_shadow_unstableaffliction_3",
    "Glyph of Voidwalker":                 "spell_shadow_summonvoidwalker",

     # Warrior 
    "Glyph of Barbaric Insults":            "ability_warrior_punishingblow",
    "Glyph of Battle":                      "ability_warrior_battleshout",
    "Glyph of Bladestorm":                  "ability_warrior_bladestorm",
    "Glyph of Blocking":                    "ability_defend",
    "Glyph of Bloodrage":                   "ability_racial_bloodrage",
    "Glyph of Bloodthirst":                 "spell_nature_bloodlust",
    "Glyph of Cleaving":                    "ability_warrior_cleave",
    "Glyph of Command":                     "ability_warrior_rallyingcry",
    "Glyph of Devastate":                   "inv_sword_11",
    "Glyph of Enduring Victory":            "ability_warrior_victoryrush",
    "Glyph of Enraged Regeneration":        "ability_warrior_focusedrage",
    "Glyph of Execution":                   "inv_sword_48",
    "Glyph of Hamstring":                   "ability_shockwave",
    "Glyph of Heroic Strike":               "ability_rogue_ambush",
    "Glyph of Charge":                      "ability_warrior_charge",
    "Glyph of Intervene":                   "ability_warrior_victoryrush",
    "Glyph of Last Stand":                  "spell_holy_ashestoashes",
    "Glyph of Mocking Blow":                "ability_warrior_punishingblow",
    "Glyph of Mortal Strike":               "ability_warrior_savageblow",
    "Glyph of Overpower":                   "ability_meleedamage",
    "Glyph of Rapid Charge":                "ability_warrior_charge",
    "Glyph of Rending":                     "ability_gouge",
    "Glyph of Resonating Power":            "spell_nature_thunderclap",
    "Glyph of Revenge":                     "ability_warrior_revenge",
    "Glyph of Shattering Throw":            "ability_warrior_shatteringthrow",
    "Glyph of Shield Wall":                 "ability_warrior_shieldwall",
    "Glyph of Shockwave":                   "ability_warrior_shockwave",
    "Glyph of Spell Reflection":            "ability_warrior_shieldreflection",
    "Glyph of Sunder Armor":                "ability_warrior_sunder",
    "Glyph of Sweeping Strikes":            "ability_rogue_slicedice",
    "Glyph of Taunt":                       "spell_nature_reincarnation",
    "Glyph of Thunder Clap":                "spell_nature_thunderclap",
    "Glyph of Victory Rush":                "ability_warrior_victoryrush",
    "Glyph of Vigilance":                   "ability_warrior_vigilance",
    "Glyph of Whirlwind":                   "ability_whirlwind",

}

# Placeholder to override glyph icon with custom ones
GLYPH_ICON_MAP_OVERRIDE: dict[str, str] = {
}